### ISSUE TITLE
Getting data error for a valid string in Python 2.7.17 & trafaret v2.0.2

### ISSUE THREAD

**Issue by johnprakashgithub** [Deepwalker/trafaret#102]
\>>> import trafaret as t
\>>> **t.String().check("test")**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/miniconda/envs/tools/lib/python2.7/site-packages/trafaret/base.py", line 115, in check
    return self.check_and_return(value)
  File "/Users/user/miniconda/envs/tools/lib/python2.7/site-packages/trafaret/base.py", line 469, in check_and_return
    self._failure(self.TYPE_ERROR_MESSAGE, value=value, code=self.TYPE_ERROR_CODE)
  File "/Users/user/miniconda/envs/tools/lib/python2.7/site-packages/trafaret/base.py", line 130, in _failure
    raise DataError(error=error, value=value, trafaret=self, code=code)
**trafaret.dataerror.DataError: value is not a string**
\>>> t.String().check(u"test")
u'test'
\>>>

**Comment by Deepwalker** [comment]
Yes, this is new behaviour in 2.0. String is python unicode string. Bytes – for bytes, and AnyString when you do not care.
